{
 "title": "TSP (TS Analyzer)",
 "description": "TSP, plugin analyze, bitrate_monitor, continuity",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "TS Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    { "expr": "tsp_analyze_ts_bitrate", "legendFormat": "TS: {{source}}" },
    { "expr": "tsp_bitrate_monitor_ts_bitrate", "legendFormat": "TS: {{source}}" },
    {
     "expr": "tsp_bitrate_monitor_net_bitrate",
     "legendFormat": "NET: {{source}} "
    }
   ]
  },
  {
   "title": "Continuity Error",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pkt/s" } },
   "targets": [
    {
     "expr": "round(increase(tsp_analyze_ts_pid_discontinuities[$__interval]))",
     "legendFormat": "{{pid}}"
    }
   ]
  },
  {
   "title": "TS PID Structure",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tsp_analyze_ts_pid_bitrate",
     "legendFormat": "PID {{pid_hexadecimal}} ({{description}})"
    }
   ]
  },
  {
   "title": "TS PID Structure",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "tsp_analyze_ts_pid_bitrate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Invalid TS Sync Packets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(delta(tsp_analyze_ts_packet_invalid_sync{}[$__range])))",
     "legendFormat": "PID {{pid_hexadecimal}}, {{description}}"
    }
   ]
  },
  {
   "title": "Total Duplicated Packets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(delta(tsp_analyze_ts_pid_duplicated{}[$__range])))",
     "legendFormat": "PID {{pid_hexadecimal}}, {{description}}"
    }
   ]
  },
  {
   "title": "Transport Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(delta(tsp_analyze_ts_packet_tei_count{}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Continuity Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(delta(tsp_continuity_error_count{}[$__range])))",
     "legendFormat": "{{pid_hexadecimal}}"
    }
   ]
  },
  {
   "title": "Continuity Error (Total)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tsp_continuity_error_count{})",
     "legendFormat": "{{pid_hexadecimal}}"
    }
   ]
  },
  {
   "title": "PCR PID Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tsp_analyze_ts_pid_pcr_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Unreferenced PID Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tsp_analyze_ts_pid_unreferenced_count{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PID Continuity Errors",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(tsp_analyze_ts_pid_discontinuities[$__interval])",
     "legendFormat": "PID {{pid_hexadecimal}}, {{description}}"
    }
   ]
  },
  {
   "title": "PID Repetition (ms) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "tsp_analyze_ts_pid_min_repitition_ms{}",
     "legendFormat": "Min Repetition:  PID {{pid_hexadecimal}}"
    },
    {
     "expr": "tsp_analyze_ts_pid_max_repitition_ms{}",
     "legendFormat": "Max Repetition: PID {{pid_hexadecimal}}"
    }
   ]
  },
  {
   "title": "PID Repetition (pkt)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "tsp_analyze_ts_pid_min_repitition_ms{}",
     "legendFormat": "Min Repetition: PID {{pid_hexadecimal}}"
    },
    {
     "expr": "tsp_analyze_ts_pid_max_repitition_ms{}",
     "legendFormat": "Max Repetition: PID {{pid_hexadecimal}}"
    }
   ]
  }
 ]
}