{
 "title": "TSP (SRT Statistics)",
 "description": "TSP, srt-statistics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Global RTT (ms) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "tsp_srt_statistic_global_instant_rtt_ms",
     "legendFormat": "RTT: {{source}}"
    }
   ]
  },
  {
   "title": "Packets (pkt/sec)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(tsp_srt_statistic_send_packets[$__rate_interval])",
     "legendFormat": "Send packets (pkt/s): {{source}}"
    }
   ]
  },
  {
   "title": "Lost Packets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(delta(tsp_srt_statistic_send_lost_packets{}[$__range]))",
     "legendFormat": "Send lost packets: {{source}}"
    }
   ]
  },
  {
   "title": "Dropped Packets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(delta(tsp_srt_statistic_send_dropped_packets{}[$__range]))",
     "legendFormat": "Send dropped packets: {{source}}"
    }
   ]
  },
  {
   "title": "Retransmit Packets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(delta(tsp_srt_statistic_send_retransmit_packets{}[$__range]))",
     "legendFormat": "Send retransmit packets: {{source}}"
    }
   ]
  },
  {
   "title": "Packets (pkt/s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(tsp_srt_statistic_receive_packets[$__rate_interval])",
     "legendFormat": "Receive packets (pkt/s): {{source}}"
    }
   ]
  },
  {
   "title": "Lost Packets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(delta(tsp_srt_statistic_receive_lost_packets{}[$__range]))",
     "legendFormat": "Receive lost packets: {{source}}"
    }
   ]
  },
  {
   "title": "Dropped Packets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(delta(tsp_srt_statistic_receive_dropped_packets{}[$__range]))",
     "legendFormat": "Receive dropped packets: {{source}}"
    }
   ]
  },
  {
   "title": "Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(tsp_srt_statistic_receive_bytes[$__rate_interval])*8",
     "legendFormat": "Receive bitrate: {{source}}"
    },
    {
     "expr": "rate(tsp_srt_statistic_send_bytes[$__rate_interval])*8",
     "legendFormat": "Send bitrate: {{source}}"
    }
   ]
  },
  {
   "title": "Delivery delay (ms) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "tsp_srt_statistic_receive_instant_delivery_delay_ms",
     "legendFormat": "Receive delivery delay: {{source}}"
    },
    {
     "expr": "tsp_srt_statistic_send_instant_delivery_delay_ms",
     "legendFormat": "Send delivery delay: {{source}}"
    }
   ]
  }
 ]
}